version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m smyth
    environment:
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-000000000000}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-}
      SALEOR_URL: ${SALEOR_URL:?SALEOR_URL env var is required}
      ENVIRONMENT: ${USER:?You need to have a USER env var}-DEV-LOCAL
      PROJECT_NAME: "my-project"
      SSM_APP_CONFIG_PATH: "${USER:?You need to have a USER env var}-DEV-LOCAL-marina-adyen/saleor_config"
      VERSION: "0.1.0"
    volumes:
      - ./src/:/app/src/
      - ./libs/:/app/libs/
      - ./pyproject.toml:/app/pyproject.toml
    ports:
      - "8090:8080"
      - "5678:5678"  # VSCode debugger
